def seed_volunteers():
    return [
        {
            "id": "vol-1",
            "name": "Anita",
            "skills": ["medical", "food distribution", "logistics"],
            "availability": True,
            "location": "Village A",
        },
        {
            "id": "vol-2",
            "name": "Rahul",
            "skills": ["water", "logistics", "shelter"],
            "availability": True,
            "location": "Village B",
        },
        {
            "id": "vol-3",
            "name": "Farah",
            "skills": ["education", "child support", "medical"],
            "availability": False,
            "location": "Town Center",
        },
        {
            "id": "vol-4",
            "name": "Joseph",
            "skills": ["shelter", "food distribution", "transport"],
            "availability": True,
            "location": "City Relief Hub",
        },
        {
            "id": "vol-5",
            "name": "Meera",
            "skills": ["water", "community outreach", "logistics"],
            "availability": True,
            "location": "Area Sunrise",
        },
        {
            "id": "vol-6",
            "name": "Daniel",
            "skills": ["medical", "transport", "rapid response"],
            "availability": True,
            "location": "Town Center",
        },
        {
            "id": "vol-7",
            "name": "Kavya",
            "skills": ["education", "food distribution", "child support"],
            "availability": True,
            "location": "Village C",
        },
        {
            "id": "vol-8",
            "name": "Imran",
            "skills": ["shelter", "water", "transport"],
            "availability": True,
            "location": "Area Riverbank",
        },
        {
            "id": "vol-9",
            "name": "Priya",
            "skills": ["medical", "triage", "community outreach"],
            "availability": True,
            "location": "Village A",
        },
        {
            "id": "vol-10",
            "name": "Sandeep",
            "skills": ["food distribution", "transport", "logistics"],
            "availability": True,
            "location": "Village B",
        },
        {
            "id": "vol-11",
            "name": "Asha",
            "skills": ["education", "child support", "community outreach"],
            "availability": True,
            "location": "Town Center",
        },
        {
            "id": "vol-12",
            "name": "Farhan",
            "skills": ["shelter", "logistics", "rapid response"],
            "availability": True,
            "location": "Camp North",
        },
    ]
